#
#  Makefile for Xinu downloader
#

all:
		(cd lib   ; make all)
		(cd cmd   ; make all)
		(cd lsi11 ; make all)
		(cd vax   ; make all)

install:
		(cd lib   ; make install)
		(cd cmd   ; make install)
		(cd lsi11 ; make install)
		(cd vax   ; make install)

clean:
		(cd lib   ; make clean)
		(cd cmd   ; make clean)
		(cd lsi11 ; make clean)
		(cd vax   ; make clean)
