.TH GETPID 2
.SH NAME
getpid \- return the process id of the currently running process
.SH SYNOPSIS
.B int
.B getpid()
.fi
.SH DESCRIPTION
.I Getpid
returns the process id of the currently executing process.
It is necessary to be able to identify one's self in order to
perform some operations (e.g., change one's scheduling priority).
