.TH DOT2IP 3
.SH NAME
dot2ip \- convert dotted decimal notation to an IP address
.SH SYNOPSIS
.nf
.B int dot2ip(ip, b1, b2, b3, b4)
.B IPaddr ip;
.B int	b1;
.B int	b2;
.B int	b3;
.B int	b4;
.br
.SH DESCRIPTION
Procedure
.I dot2ip
converts an Internet (IP) address from dotted decimal notation
to its 32-bit integer form and stores it in argument \f2ip\f1.
Each of the arguments \f2b1\f1, \f2b2\f1, \f2b3\f1,
and \f2b4\f1, gives the value of one byte of the internet
address.
